2025-09-24 23:18:22,867 INFO    MainThread:43708 [wandb_setup.py:_flush():81] Current SDK version is 0.22.0
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_setup.py:_flush():81] Configure stats pid to 43708
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_setup.py:_flush():81] Loading settings from C:\Users\jwali\.config\wandb\settings
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_setup.py:_flush():81] Loading settings from C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\settings
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_init.py:setup_run_log_directory():686] Logging user logs to C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\run-20250924_231822-dfxp2sw0\logs\debug.log
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_init.py:setup_run_log_directory():687] Logging internal logs to C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\run-20250924_231822-dfxp2sw0\logs\debug-internal.log
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_init.py:init():813] calling init triggers
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_init.py:init():818] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-24 23:18:22,868 INFO    MainThread:43708 [wandb_init.py:init():861] starting backend
2025-09-24 23:18:25,132 INFO    MainThread:43708 [wandb_init.py:init():864] sending inform_init request
2025-09-24 23:18:25,170 INFO    MainThread:43708 [wandb_init.py:init():872] backend started and connected
2025-09-24 23:18:25,171 INFO    MainThread:43708 [wandb_init.py:init():942] updated telemetry
2025-09-24 23:18:25,173 INFO    MainThread:43708 [wandb_init.py:init():966] communicating run to backend with 90.0 second timeout
2025-09-24 23:18:25,576 INFO    MainThread:43708 [wandb_init.py:init():1017] starting run threads in backend
2025-09-24 23:18:26,374 INFO    MainThread:43708 [wandb_run.py:_console_start():2506] atexit reg
2025-09-24 23:18:26,374 INFO    MainThread:43708 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-09-24 23:18:26,374 INFO    MainThread:43708 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-09-24 23:18:26,374 INFO    MainThread:43708 [wandb_run.py:_redirect():2446] Redirects installed.
2025-09-24 23:18:26,378 INFO    MainThread:43708 [wandb_init.py:init():1057] run started, returning control to user process
2025-09-24 23:22:13,194 INFO    wandb-AsyncioManager-main:43708 [service_client.py:_forward_responses():84] Reached EOF.
2025-09-24 23:22:13,194 INFO    wandb-AsyncioManager-main:43708 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-09-24 23:22:13,704 ERROR   wandb-AsyncioManager-main:43708 [asyncio_manager.py:fn_wrap_exceptions():183] Uncaught exception in run_soon callback.
Traceback (most recent call last):
  File "C:\Users\jwali\anaconda3\Lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 181, in fn_wrap_exceptions
    await fn()
  File "C:\Users\jwali\anaconda3\Lib\site-packages\wandb\sdk\lib\service\service_client.py", line 65, in _send_server_request
    await self._writer.drain()
  File "C:\Users\jwali\anaconda3\Lib\asyncio\streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "C:\Users\jwali\anaconda3\Lib\asyncio\streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
