2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_setup.py:_flush():81] Current SDK version is 0.22.0
2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_setup.py:_flush():81] Configure stats pid to 33392
2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_setup.py:_flush():81] Loading settings from C:\Users\jwali\.config\wandb\settings
2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_setup.py:_flush():81] Loading settings from C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\settings
2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-09-24 23:00:23,154 INFO    MainThread:33392 [wandb_init.py:setup_run_log_directory():686] Logging user logs to C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\run-20250924_230023-att6derx\logs\debug.log
2025-09-24 23:00:23,155 INFO    MainThread:33392 [wandb_init.py:setup_run_log_directory():687] Logging internal logs to C:\Users\jwali\Downloads\Kaggle\Music recomendation\wandb\run-20250924_230023-att6derx\logs\debug-internal.log
2025-09-24 23:00:23,155 INFO    MainThread:33392 [wandb_init.py:init():813] calling init triggers
2025-09-24 23:00:23,155 INFO    MainThread:33392 [wandb_init.py:init():818] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-24 23:00:23,155 INFO    MainThread:33392 [wandb_init.py:init():861] starting backend
2025-09-24 23:00:25,431 INFO    MainThread:33392 [wandb_init.py:init():864] sending inform_init request
2025-09-24 23:00:25,492 INFO    MainThread:33392 [wandb_init.py:init():872] backend started and connected
2025-09-24 23:00:25,495 INFO    MainThread:33392 [wandb_init.py:init():942] updated telemetry
2025-09-24 23:00:25,497 INFO    MainThread:33392 [wandb_init.py:init():966] communicating run to backend with 90.0 second timeout
2025-09-24 23:00:26,065 INFO    MainThread:33392 [wandb_init.py:init():1017] starting run threads in backend
2025-09-24 23:00:27,521 INFO    MainThread:33392 [wandb_run.py:_console_start():2506] atexit reg
2025-09-24 23:00:27,522 INFO    MainThread:33392 [wandb_run.py:_redirect():2354] redirect: wrap_raw
2025-09-24 23:00:27,522 INFO    MainThread:33392 [wandb_run.py:_redirect():2423] Wrapping output streams.
2025-09-24 23:00:27,522 INFO    MainThread:33392 [wandb_run.py:_redirect():2446] Redirects installed.
2025-09-24 23:00:27,528 INFO    MainThread:33392 [wandb_init.py:init():1057] run started, returning control to user process
2025-09-24 23:00:31,250 INFO    wandb-AsyncioManager-main:33392 [service_client.py:_forward_responses():84] Reached EOF.
2025-09-24 23:00:31,250 INFO    wandb-AsyncioManager-main:33392 [mailbox.py:close():137] Closing mailbox, abandoning 1 handles.
2025-09-24 23:00:31,690 ERROR   wandb-AsyncioManager-main:33392 [asyncio_manager.py:fn_wrap_exceptions():183] Uncaught exception in run_soon callback.
Traceback (most recent call last):
  File "C:\Users\jwali\anaconda3\Lib\site-packages\wandb\sdk\lib\asyncio_manager.py", line 181, in fn_wrap_exceptions
    await fn()
  File "C:\Users\jwali\anaconda3\Lib\site-packages\wandb\sdk\lib\service\service_client.py", line 65, in _send_server_request
    await self._writer.drain()
  File "C:\Users\jwali\anaconda3\Lib\asyncio\streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "C:\Users\jwali\anaconda3\Lib\asyncio\streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
